language: python
python:
  - "2.7"
  - "3.5"
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install pip --upgrade
  - pip install setuptools==25.1.0
  - pip install -r requirements_dev.txt
  - python setup.py install
  - ccc_client --version

# run_tests.py runs everything under the script: tag so only put commands
# under it that we want to run (and want to be able to run) as local tests
script: 
  - ./scripts/check.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
